[workspace]
members = ["hick", "hick-trace", "mdns-proto", "hick-udp", "hick-reactor", "hick-compio", "hick-mio", "hick-smoltcp", "hick-embassy"]
resolver = "3"

[workspace.dependencies]
bytes = { version = "1", default-features = false }
hick = { version = "0.3", path = "hick", default-features = false }
hick-trace = { version = "0.1", path = "hick-trace", default-features = false }
mdns-proto = { version = "0.4", path = "mdns-proto", default-features = false }
hick-udp = { version = "0.1", path = "hick-udp", default-features = false }
hick-reactor = { version = "0.3", path = "hick-reactor", default-features = false }
hick-compio = { version = "0.3", path = "hick-compio", default-features = false }
hick-mio = { version = "0.1", path = "hick-mio", default-features = false }
hick-smoltcp = { version = "0.3", path = "hick-smoltcp", default-features = false }
hick-embassy = { version = "0.3", path = "hick-embassy", default-features = false }
tracing = { version = "0.1", default-features = false }
metrics = { version = "0.24", default-features = false }
portable-atomic = { version = "1", default-features = false, features = ["fallback"] }
defmt = { version = "1", default-features = false }
thiserror = { version = "2", default-features = false }
derive_more = { version = "2", default-features = false, features = ["display", "from", "is_variant", "unwrap", "try_unwrap"] }
rand = { version = "0.10", default-features = false }
rand_core = { version = "0.10", default-features = false }
smol_str = { version = "0.3", default-features = false }
slab = { version = "0.4", default-features = false }
futures = { version = "0.3", default-features = false }
getifs = { version = "0.6" }
libc = { version = "0.2" }
mio = { version = "1", default-features = false }
tracing-core = { version = "0.1" }
ctor = { version = "1" }

[workspace.lints.rust]
rust_2018_idioms = "warn"
single_use_lifetimes = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage)'] }
